NAME = push_swap.a
CC = cc
CFLAGS = -Wall -Wextra -Werror
PRINTF_PATH = ./ft_printf
PRINTF_LIB  = $(PRINTF_PATH)/libftprintf.a
PRINTF_INC  = -I $(PRINTF_PATH)
SOURCES = parsing_arg.c utils.c main.c
OBJECTS = $(SOURCES:.c=.o)

all: $(NAME)
$(NAME) : $(OBJECTS)
	ar rcs $(NAME) $(OBJECTS)
%.o: %.c push_swap.h
	$(CC) $(CFLAGS) -c $< -o $@
clean:
	rm -f $(OBJECTS)
fclean: clean
	rm -f $(NAME)
re : fclean all
PHONY: all clean fclean re